[build]
  # Build command for the frontend
  command = "npm run build:client"
  # Directory to publish (where the built frontend files are)
  publish = "dist/public"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Set node version
[build.environment]
  NODE_VERSION = "18"

# Optional: Headers for better caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
